server.port=${PORT:10000}
server.address=0.0.0.0

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.jpa.open-in-view=false