spring.application.name=csd230-lecture-2.11.1-react-in-class-exercise

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=Zm9yLWxhYi02LXNlY3VyZS1yYmFjLWltcGxlbWVudGF0aW9uLXRpcnRocmFqc2luaC1wYXJtYXItMjAyNg==
jwt.access-token-validity=3600000
